package model

import (
	"fmt"
)

// See 13.3 Error Codes

type MOQT_SESSION_TERMINATION_ERROR_CODE uint64

const (
	MOQT_SESSION_TERMINATION_ERROR_CODE_NO_ERROR                   MOQT_SESSION_TERMINATION_ERROR_CODE = 0x0 // Used while terminating the session gracefully
	MOQT_SESSION_TERMINATION_ERROR_CODE_INTERNAL_ERROR             MOQT_SESSION_TERMINATION_ERROR_CODE = 0x1 // Commonly used to let the peer know the error is caused from internal logic
	MOQT_SESSION_TERMINATION_ERROR_CODE_PROTOCOL_VIOLATION         MOQT_SESSION_TERMINATION_ERROR_CODE = 0x3
	MOQT_SESSION_TERMINATION_ERROR_CODE_KEY_VALUE_FORMATTING_ERROR MOQT_SESSION_TERMINATION_ERROR_CODE = 0x6
	MOQT_SESSION_TERMINATION_ERROR_CODE_TOO_MANY_REQUESTS          MOQT_SESSION_TERMINATION_ERROR_CODE = 0x7 // A message is received with equal or larger "Request Id" than the "MAX_REQUEST_ID" of session's
	MOQT_SESSION_TERMINATION_ERROR_CODE_INVALID_PATH               MOQT_SESSION_TERMINATION_ERROR_CODE = 0x8
	MOQT_SESSION_TERMINATION_ERROR_CODE_INVALID_AUTHORITY          MOQT_SESSION_TERMINATION_ERROR_CODE = 0x19
)

type MOQT_SESSION_TERMINATION_ERROR struct {
	ErrorCode    MOQT_SESSION_TERMINATION_ERROR_CODE
	ReasonPhrase MoqtReasonPhrase
}

func (e MOQT_SESSION_TERMINATION_ERROR) Error() string {
	return fmt.Sprintf("MOQT Session Termination Error - Code: %#X, Reason: %s", e.ErrorCode, e.ReasonPhrase)
}

type MOQT_REQUEST_ERROR_CODE uint64

const (
	MOQT_REQUEST_ERROR_CODE_INTERNAL_ERROR             MOQT_REQUEST_ERROR_CODE = 0x0
	MOQT_REQUEST_ERROR_CODE_UNAUTHORIZED               MOQT_REQUEST_ERROR_CODE = 0x1
	MOQT_REQUEST_ERROR_CODE_TIMEOUT                    MOQT_REQUEST_ERROR_CODE = 0x2
	MOQT_REQUEST_ERROR_CODE_NOT_SUPPORTED              MOQT_REQUEST_ERROR_CODE = 0x3
	MOQT_REQUEST_ERROR_CODE_MALFORMED_AUTH_TOKEN       MOQT_REQUEST_ERROR_CODE = 0x4
	MOQT_REQUEST_ERROR_CODE_EXPIRED_AUTH_TOKEN         MOQT_REQUEST_ERROR_CODE = 0x5
	MOQT_REQUEST_ERROR_CODE_DOES_NOT_EXIST             MOQT_REQUEST_ERROR_CODE = 0x10
	MOQT_REQUEST_ERROR_CODE_INVALID_RANGE              MOQT_REQUEST_ERROR_CODE = 0x11
	MOQT_REQUEST_ERROR_CODE_MALFORMED_TRACK            MOQT_REQUEST_ERROR_CODE = 0x12
	MOQT_REQUEST_ERROR_CODE_UNINTERESTED               MOQT_REQUEST_ERROR_CODE = 0x20
	MOQT_REQUEST_ERROR_CODE_PREFIX_OVERLAP             MOQT_REQUEST_ERROR_CODE = 0x30
	MOQT_REQUEST_ERROR_CODE_INVALID_JOINING_REQUEST_ID MOQT_REQUEST_ERROR_CODE = 0x32
	MOQT_REQUEST_ERROR_CODE_UNKNOWN_STATUS_IN_RANGE    MOQT_REQUEST_ERROR_CODE = 0x33
)

type MOQT_REQUEST_ERROR struct {
	ErrorCode    MOQT_REQUEST_ERROR_CODE
	ReasonPhrase MoqtReasonPhrase
}

func (e MOQT_REQUEST_ERROR) Error() string {
	return fmt.Sprintf("MOQT Request Error - Code: %#X, Reason: %s", e.ErrorCode, e.ReasonPhrase)
}