package model

import (
	"fmt"
)

// See 13.3 Error Codes

type MOQT_SESSION_TERMINATION_ERROR_CODE uint64

const (
	MOQT_SESSION_TERMINATION_ERROR_CODE_NO_ERROR                   MOQT_SESSION_TERMINATION_ERROR_CODE = 0x0 // Used while terminating the session gracefully
	MOQT_SESSION_TERMINATION_ERROR_CODE_INTERNAL_ERROR             MOQT_SESSION_TERMINATION_ERROR_CODE = 0x1 // Commonly used to let the peer know the error is caused from internal logic
	MOQT_SESSION_TERMINATION_ERROR_CODE_PROTOCOL_VIOLATION         MOQT_SESSION_TERMINATION_ERROR_CODE = 0x3
	MOQT_SESSION_TERMINATION_ERROR_CODE_KEY_VALUE_FORMATTING_ERROR MOQT_SESSION_TERMINATION_ERROR_CODE = 0x6
	MOQT_SESSION_TERMINATION_ERROR_CODE_INVALID_PATH               MOQT_SESSION_TERMINATION_ERROR_CODE = 0x8
	MOQT_SESSION_TERMINATION_ERROR_CODE_INVALID_AUTHORITY          MOQT_SESSION_TERMINATION_ERROR_CODE = 0x19
)

type MOQT_SESSION_TERMINATION_ERROR struct {
	ErrorCode    MOQT_SESSION_TERMINATION_ERROR_CODE
	ReasonPhrase MoqtReasonPhrase
}

func (e MOQT_SESSION_TERMINATION_ERROR) Error() string {
	return fmt.Sprintf("MOQT Session Termination Error - Code: %#X, Reason: %s", e.ErrorCode, e.ReasonPhrase)
}
